// examples/apps/lit-html-todomvc/src/form/form.js
import { html } from "lit-html"

export const form = {
  inputChange(entity, value) {
    entity.value = value
  },

  formSubmit(entity) {
    entity.value = ""
  },

  render({ value }, { notify }) {
    return html`<form
      @submit=${(event) => {
        event.preventDefault()
        notify("formSubmit", value)
      }}
    >
      <input
        placeholder="What next?"
        autofocus
        .value=${value}
        @input=${(event) => notify("inputChange", event.target.value)}
      />
      <button>Add</button>
    </form>`
  },
}

// examples/apps/web-todomvc-jsx/src/form/form.jsx
export const form = {
  inputChange(entity, value) {
    entity.value = value
  },

  formSubmit(entity) {
    entity.value = ""
  },

  render(entity, api) {
    return (
      <form
        onSubmit={(event) => {
          event.preventDefault()
          api.notify("formSubmit", entity.value)
        }}
      >
        <input
          name="value"
          placeholder="What next?"
          autoFocus
          value={entity.value}
          onInput={(event) => api.notify("inputChange", event.target.value)}
        />
        <button disabled={!entity.value}>Add</button>
      </form>
    )
  },
}
