// examples/apps/react-todomvc-rt/src/footer/index.jsx
import clsx from "clsx"

import { useNotify, useSelector } from "../store"
import { selectActiveFilter, selectTasksCount } from "../store/selectors"

const SINGLE_TASK = 1

export default function Footer() {
  const notify = useNotify()

  const tasksCount = useSelector(selectTasksCount())
  const completedTasksCount = useSelector(selectTasksCount("completed"))
  const activeTasksCount = useSelector(selectTasksCount("active"))
  const activeFilter = useSelector(selectActiveFilter)

  if (!tasksCount) return null

  return (
    <footer>
      <span>
        {activeTasksCount} item{activeTasksCount === SINGLE_TASK ? "" : "s"}{" "}
        left
      </span>

      <span className="filters">
        <a
          className={clsx({ selected: activeFilter === "all" })}
          onClick={() => notify("filterClick", "all")}
        >
          All
        </a>
        <a
          className={clsx({ selected: activeFilter === "active" })}
          onClick={() => notify("filterClick", "active")}
        >
          Active
        </a>
        <a
          className={clsx({ selected: activeFilter === "completed" })}
          onClick={() => notify("filterClick", "completed")}
        >
          Completed
        </a>
      </span>

      <a
        className={clsx({ hidden: !completedTasksCount })}
        onClick={() => notify("clearClick")}
      >
        Clear Completed
      </a>
    </footer>
  )
}

// examples/apps/lit-html-todomvc/src/footer/footer.js
import { html } from "lit-html"
import { classMap } from "lit-html/directives/class-map.js"
import { selectTasksCount } from "../store/selectors"

const SINGLE_TASK = 1

export const footer = {
  filterClick(entity, id) {
    entity.activeFilter = id
  },

  render({ activeFilter }, { notify, getEntities }) {
    const entities = getEntities()

    const tasksCount = selectTasksCount()(entities)
    const completedTasksCount = selectTasksCount("completed")(entities)
    const activeTasksCount = selectTasksCount("active")(entities)

    if (!tasksCount) return null

    return html` <footer>
      <span>
        ${activeTasksCount}
        item${activeTasksCount === SINGLE_TASK ? "" : "s"}${" "} left
      </span>

      <span class="filters">
        <a
          class=${classMap({ selected: activeFilter === "all" })}
          @click=${() => notify("filterClick", "all")}
        >
          All
        </a>
        <a
          class=${classMap({ selected: activeFilter === "active" })}
          @click=${() => notify("filterClick", "active")}
        >
          Active
        </a>
        <a
          class=${classMap({ selected: activeFilter === "completed" })}
          @click=${() => notify("filterClick", "completed")}
        >
          Completed
        </a>
      </span>

      <a
        class=${classMap({ hidden: !completedTasksCount })}
        @click=${() => notify("clearClick")}
      >
        Clear Completed
      </a>
    </footer>`
  },
}
