// examples/apps/lit-html-todomvc/src/form/form.js
import { html } from "lit-html"

export const form = {
  inputChange(entity, value) {
    entity.value = value
  },

  formSubmit(entity) {
    entity.value = ""
  },

  render({ value }, { notify }) {
    return html`<form
      @submit=${(event) => {
        event.preventDefault()
        notify("formSubmit", value)
      }}
    >
      <input
        placeholder="What next?"
        autofocus
        .value=${value}
        @input=${(event) => notify("inputChange", event.target.value)}
      />
      <button>Add</button>
    </form>`
  },
}

// examples/apps/react-todomvc-rt/src/form/index.jsx
import { useEntity, useNotify } from "../store"

export default function Form() {
  const notify = useNotify()

  const { value } = useEntity("form")
  const handleChange = (event) => notify("inputChange", event.target.value)

  const handleSubmit = (event) => {
    event.preventDefault()
    notify("formSubmit", value)
  }

  return (
    <form onSubmit={handleSubmit}>
      <input
        placeholder="What next?"
        autoFocus
        value={value}
        onChange={handleChange}
      />
      <button disabled={!value.length}>Add</button>
    </form>
  )
}
