// examples/apps/web-todomvc-jsx/src/list/list.jsx
import { classMap } from "@inglorious/web"

import { selectFilteredTasks } from "../store/selectors"

const TASKS_TO_REMOVE = 1
const DEFAULT_ID = 1
const LAST_TASK = 1
const NEXT_ID = 1

export const list = {
  formSubmit(entity, value) {
    entity.tasks.push({ id: nextId(entity.tasks), text: value })
  },

  toggleClick(entity, id) {
    const task = entity.tasks.find((task) => task.id === id)
    task.completed = !task.completed
  },

  deleteClick(entity, id) {
    const index = entity.tasks.findIndex((task) => task.id === id)
    entity.tasks.splice(index, TASKS_TO_REMOVE)
  },

  clearClick(entity) {
    entity.tasks = entity.tasks.filter((task) => !task.completed)
  },

  render(entity, api) {
    const filteredTasks = selectFilteredTasks(api.getEntities())

    return (
      <ul className="list">
        {filteredTasks.map((task) => (
          <li key={task.id}>
            <span
              className={classMap({ completed: task.completed })}
              onClick={() => api.notify("toggleClick", task.id)}
            >
              {task.text}
            </span>
            <button onClick={() => api.notify("deleteClick", task.id)}>
              x
            </button>
          </li>
        ))}
      </ul>
    )
  },
}

function nextId(tasks) {
  if (!tasks.length) return DEFAULT_ID
  return tasks[tasks.length - LAST_TASK].id + NEXT_ID
}

// examples/apps/lit-html-todomvc/src/list/list.js
import { html } from "lit-html"
import { classMap } from "lit-html/directives/class-map.js"
import { selectFilteredTasks } from "../store/selectors"

const TASKS_TO_REMOVE = 1
const DEFAULT_ID = 1
const LAST_TASK = 1
const NEXT_ID = 1

export const list = {
  formSubmit(entity, value) {
    entity.tasks.push({ id: nextId(entity.tasks), text: value })
  },

  toggleClick(entity, id) {
    const task = entity.tasks.find((task) => task.id === id)
    task.completed = !task.completed
  },

  deleteClick(entity, id) {
    const index = entity.tasks.findIndex((task) => task.id === id)
    entity.tasks.splice(index, TASKS_TO_REMOVE)
  },

  clearClick(entity) {
    entity.tasks = entity.tasks.filter((task) => !task.completed)
  },

  render(entity, { notify, getEntities }) {
    const filteredTasks = selectFilteredTasks(getEntities())

    return html`<ul>
      ${filteredTasks.map(
        (task) =>
          html`<li>
            <span
              class=${classMap({ completed: task.completed })}
              @click=${() => notify("toggleClick", task.id)}
              >${task.text}</span
            >
            <button @click=${() => notify("deleteClick", task.id)}>x</button>
          </li>`,
      )}
    </ul>`
  },
}

function nextId(tasks) {
  if (!tasks.length) return DEFAULT_ID
  return tasks[tasks.length - LAST_TASK].id + NEXT_ID
}
