// examples/apps/lit-html-todomvc/src/app.js
import { html } from "lit-html"
import { form } from "./form/form"
import { list } from "./list/list"
import { footer } from "./footer/footer"

export const app = {
  render(api) {
    const entities = api.getEntities()
    return html`${form.render(entities.form, api)}
    ${list.render(entities.list, api)} ${footer.render(entities.footer, api)}`
  },
}

// examples/apps/todomvc/src/App.jsx
import "./style.css"

import Footer from "./Footer"
import Form from "./Form"
import List from "./List"
import { Provider } from "react-redux"
import { store } from "./store"

export default function App() {
  return (
    <Provider store={store}>
      <h1>todos</h1>
      <Form />
      <List />
      <Footer />
    </Provider>
  )
}
