// examples/apps/lit-html-todomvc/src/list/list.js
import { html } from "lit-html"
import { classMap } from "lit-html/directives/class-map.js"
import { selectFilteredTasks } from "../store/selectors"

const TASKS_TO_REMOVE = 1
const DEFAULT_ID = 1
const LAST_TASK = 1
const NEXT_ID = 1

export const list = {
  formSubmit(entity, value) {
    entity.tasks.push({ id: nextId(entity.tasks), text: value })
  },

  toggleClick(entity, id) {
    const task = entity.tasks.find((task) => task.id === id)
    task.completed = !task.completed
  },

  deleteClick(entity, id) {
    const index = entity.tasks.findIndex((task) => task.id === id)
    entity.tasks.splice(index, TASKS_TO_REMOVE)
  },

  clearClick(entity) {
    entity.tasks = entity.tasks.filter((task) => !task.completed)
  },

  render(entity, { notify, getEntities }) {
    const filteredTasks = selectFilteredTasks(getEntities())

    return html`<ul>
      ${filteredTasks.map(
        (task) =>
          html`<li>
            <span
              class=${classMap({ completed: task.completed })}
              @click=${() => notify("toggleClick", task.id)}
              >${task.text}</span
            >
            <button @click=${() => notify("deleteClick", task.id)}>x</button>
          </li>`,
      )}
    </ul>`
  },
}

function nextId(tasks) {
  if (!tasks.length) return DEFAULT_ID
  return tasks[tasks.length - LAST_TASK].id + NEXT_ID
}

// examples/apps/todomvc/src/List.jsx
import { clsx } from "clsx"

import { useNotify, useSelector } from "./store"
import { selectFilteredTasks } from "./store/selectors"

export default function List() {
  const notify = useNotify()

  const tasks = useSelector(selectFilteredTasks)

  return (
    <ul>
      {tasks.map((task) => (
        <li key={task.id}>
          <span
            className={clsx({ completed: task.completed })}
            onClick={() => notify("toggleClick", task.id)}
          >
            {task.text}
          </span>{" "}
          <button onClick={() => notify("deleteClick", task.id)}>x</button>
        </li>
      ))}
    </ul>
  )
}
