// examples/apps/lit-html-todomvc/src/footer/footer.js
import { html } from "lit-html"
import { classMap } from "lit-html/directives/class-map.js"
import { selectTasksCount } from "../store/selectors"

const SINGLE_TASK = 1

export const footer = {
  filterClick(entity, id) {
    entity.activeFilter = id
  },

  render({ activeFilter }, { notify, getEntities }) {
    const entities = getEntities()

    const tasksCount = selectTasksCount()(entities)
    const completedTasksCount = selectTasksCount("completed")(entities)
    const activeTasksCount = selectTasksCount("active")(entities)

    if (!tasksCount) return null

    return html` <footer>
      <span>
        ${activeTasksCount}
        item${activeTasksCount === SINGLE_TASK ? "" : "s"}${" "} left
      </span>

      <span class="filters">
        <a
          class=${classMap({ selected: activeFilter === "all" })}
          @click=${() => notify("filterClick", "all")}
        >
          All
        </a>
        <a
          class=${classMap({ selected: activeFilter === "active" })}
          @click=${() => notify("filterClick", "active")}
        >
          Active
        </a>
        <a
          class=${classMap({ selected: activeFilter === "completed" })}
          @click=${() => notify("filterClick", "completed")}
        >
          Completed
        </a>
      </span>

      <a
        class=${classMap({ hidden: !completedTasksCount })}
        @click=${() => notify("clearClick")}
      >
        Clear Completed
      </a>
    </footer>`
  },
}

// examples/apps/web-todomvc-tsx/src/footer/footer.tsx
import { classMap } from "@inglorious/web"

import { selectTasksCount } from "../store/selectors"

const SINGLE_TASK = 1

export const footer = {
  filterClick(entity, id) {
    entity.activeFilter = id
  },

  render(entity, api) {
    const entities = api.getEntities()

    const tasksCount = selectTasksCount()(entities)
    const completedTasksCount = selectTasksCount("completed")(entities)
    const activeTasksCount = selectTasksCount("active")(entities)

    if (!tasksCount) return null

    return (
      <footer>
        <span>
          {activeTasksCount}
          item{activeTasksCount === SINGLE_TASK ? "" : "s"} left
        </span>

        <span className="filters">
          <a
            className={classMap({ selected: entity.activeFilter === "all" })}
            onClick={() => api.notify("filterClick", "all")}
          >
            All
          </a>
          <a
            className={classMap({ selected: entity.activeFilter === "active" })}
            onClick={() => api.notify("filterClick", "active")}
          >
            Active
          </a>
          <a
            className={classMap({
              selected: entity.activeFilter === "completed",
            })}
            onClick={() => api.notify("filterClick", "completed")}
          >
            Completed
          </a>
        </span>

        <a
          className={classMap({ hidden: !completedTasksCount })}
          onClick={() => api.notify("clearClick")}
        >
          Clear Completed
        </a>
      </footer>
    )
  },
}
